server:
  port: 8083

spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:orderservice
    application:
        name: orderservice
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

